import Head from "next/head";
import Image from "next/image";
import React, { EventHandler, useState } from "react";
import styles from "../styles/Home.module.css";
import client from "../libs/client";

const inputContainer = {
  display: "flex",
  alignItems: "center",
  width: "100%",
};

const inputStyle = {
  flex: 4,
  padding: "3px",
  border: "1px solid white",
};

const buttonStyle = {
  width: "200px",
  margin: "60px",
  padding: "30px",
  background: "black",
  color: "white",
  border: "1px solid white",
};
export default function Home() {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");

  const handleTitle = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTitle(e.target.value);
  };

  const handleContent = (e: React.ChangeEvent<HTMLInputElement>) => {
    setContent(e.target.value);
  };

  const handlePost = async () => {
    await client();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <h3>Title</h3>
        <div style={inputContainer}>
          <input type="text" style={inputStyle} onChange={handleTitle} />
        </div>
        <h3>Content</h3>
        <div style={inputContainer}>
          <input type="text" style={inputStyle} onChange={handleContent} />
        </div>
        <button style={buttonStyle}>POST</button>
      </main>
    </div>
  );
}
